version: '3.4'

services:
  clay.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - JWT_SECRET=SECRET_KEY
      - DATABASE_CONNECTIONSTRING=Server=sqlserver;Database=Clay;Trusted_Connection=true;User Id=sa;Password=SqlServer2019!;TrustServerCertificate=True;Integrated Security=false
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  sqlserver:
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - ./Clay.Infrastructure/sql/data:/var/opt/mssql/data